name: CI/CD

on:
  release:
    types:
      - published
  push:
  pull_request:
    branches: [ main ]

env:
  AWS_DEPLOY_STAGE: dev
  AWS_DEPLOY_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEPLOY_REGION }}

      - name: install dependencies
        working-directory: ./backend
        run: npm install

      - name: build sls project
        working-directory: ./backend
        run: npm run build

  deploy:
    if: github.event_name == 'release'

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEPLOY_REGION }}

      - name: install dependencies
        working-directory: ./backend
        run: npm install

      - name: deploy sls project
        working-directory: ./backend
        run: npm run deploy


